name: UX Traveller
favicon: null
layout_spectrum: 0.35109466360881925
typography_spectrum: 0.2570633601862937
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7001794951502234
  lightness: 0.041965164709836245
  saturation: 0.7615465861745179
  rhythmicContrast: 0.4992148850578815
purpose: []
